--- #YAML:1.0
name:               WWW-Pusher
version:            0.03
abstract:           Interface to the Pusher WebSockets API
author:
    - Squeeks <squeek@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::MD5:  2.39
    Digest::SHA:  5.48
    JSON:         0
    LWP:          0
    perl:         5.008
    Test::More:   0
    URI:          0
resources:
    repository:  http://github.com/squeeks/WWW-Pusher
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
